kind: Template
apiVersion: v1
template: data-loader
metadata:
  name: data-loader
objects:

- kind: Job
  apiVersion: batch/v1
  metadata:
    name: ${JOB_NAME}
  spec:
    parallelism: 1
    completions: 1
    template:
      metadata:
        name: ${JOB_NAME}
      spec:
        containers:
          - name: data-loader
            image: docker.io/rsimmond/loader
            env:
              - name: SERVER
                value: ${SERVER}
              - name: DBNAME
                value: ${DBNAME}
              - name: USER
                value: ${USER}
              - name: PASSWORD
                value: ${PASSWORD}
        restartPolicy: OnFailure

parameters:
  - name: JOB_NAME
    from: "jdsl-[a-z0-9]{4}"
    generate: expression
    description: unique name for this job run
